@Library('jenkins-shared-lib') _

pythonServicePipeline(
  serviceName: 'recommendationservice',
  servicePath: 'src/recommendationservice',
  gitUrl: 'https://github.com/linbingdouzhe/microservices-demo.git',
  gitBranch: 'main',
  manifestPath: 'kubernetes-manifests/recommendationservice.yaml',
  manifestRepoSshUrl: 'git@github.com:linbingdouzhe/microservices-demo.git',
  deployRegistry: 'localhost:30500'
)
