@Library('jenkins-shared-lib') _

pythonServicePipeline(
  serviceName: 'recommendationservice',
  servicePath: 'src/recommendationservice',
  gitUrl: 'https://github.com/linbingdouzhe/microservices-demo.git',
  gitBranch: 'main'
)
