@Library('jenkins-shared-lib') _

pythonServicePipeline(
  serviceName: 'emailservice',
  servicePath: 'src/emailservice',
  gitUrl: 'https://github.com/linbingdouzhe/microservices-demo.git',
  gitBranch: 'main',
  manifestPath: 'kubernetes-manifests/emailservice.yaml',
  manifestRepoSshUrl: 'git@github.com:linbingdouzhe/microservices-demo.git'
)
